version: '3.7'

volumes:
  local_postgres_data: {}

services:
  web:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app/
    links:
      - redis
    ports:
    - 8000:8000
    env_file:
    - ./env/.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
    - local_postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=situationroom
    - POSTGRES_PASSWORD=situationroom
    - POSTGRES_DB=situationroom_dev
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery_worker:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: situationroom_celery_celery_worker
    command: celery -A situationroom worker -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - db
      - web

  celery_beat:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: situationroom_celery_celery_beat
    command: celery -A situationroom beat -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - db
      - web
  flower:
    image: mher/flower
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./env/.env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
      - web 
      - celery_beat
      - celery_worker

