# Generated by Django 3.2.6 on 2022-01-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='wieght',
            new_name='weight',
        ),
    ]
