# Generated by Django 3.2.6 on 2022-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('nhl_api_id', models.IntegerField(null=True)),
                ('division', models.CharField(choices=[('ATL', 'Atlantic'), ('METRO', 'Metropolitan'), ('PAC', 'Pacific'), ('CEN', 'Central')], max_length=50, null=True)),
            ],
        ),
    ]
