# Generated by Django 3.2.6 on 2022-01-08 15:58

from django.db import migrations


default_teams = [
    {
        "city": "New Jersey",
        "team_name": "Devils",
        "nhl_api_id": 1,
        "division": "Metropolitan",
    },
    {
        "city": "New YorkI",
        "team_name": "Islanders",
        "nhl_api_id": 2,
        "division": "Metropolitan",
    },
    {
        "city": "New YorkR",
        "team_name": "Rangers",
        "nhl_api_id": 3,
        "division": "Metropolitan",
    },
    {
        "city": "Philadelphia",
        "team_name": "Flyers",
        "nhl_api_id": 4,
        "division": "Metropolitan",
    },
    {
        "city": "Pittsburgh",
        "team_name": "Penguins",
        "nhl_api_id": 5,
        "division": "Metropolitan",
    },
    {
        "city": "Boston",
        "team_name": "Bruins",
        "nhl_api_id": 6,
        "division": "Atlantic",
    },
    {
        "city": "Buffalo",
        "team_name": "Sabres",
        "nhl_api_id": 7,
        "division": "Atlantic",
    },
    {
        "city": "Montreal",
        "team_name": "Canadiens",
        "nhl_api_id": 8,
        "division": "Atlantic",
    },
    {
        "city": "Ottawa",
        "team_name": "Senators",
        "nhl_api_id": 9,
        "division": "Atlantic",
    },
    {
        "city": "Toronto",
        "team_name": "Maple Leafs",
        "nhl_api_id": 10,
        "division": "Atlantic",
    },
    {
        "city": "Carolina",
        "team_name": "Hurricanes",
        "nhl_api_id": 12,
        "division": "Metropolitan",
    },
    {
        "city": "Florida",
        "team_name": "Panthers",
        "nhl_api_id": 13,
        "division": "Atlantic",
    },
    {
        "city": "Tampa Bay",
        "team_name": "Lightning",
        "nhl_api_id": 14,
        "division": "Atlantic",
    },
    {
        "city": "Washington",
        "team_name": "Capitals",
        "nhl_api_id": 15,
        "division": "Metropolitan",
    },
    {
        "city": "Chicago",
        "team_name": "Blackhawks",
        "nhl_api_id": 16,
        "division": "Central",
    },
    {
        "city": "Detroit",
        "team_name": "Red Wings",
        "nhl_api_id": 17,
        "division": "Atlantic",
    },
    {
        "city": "Nashville",
        "team_name": "Predators",
        "nhl_api_id": 18,
        "division": "Central",
    },
    {
        "city": "St Louis",
        "team_name": "Blues",
        "nhl_api_id": 19,
        "division": "Central",
    },
    {
        "city": "Calgary",
        "team_name": "Flames",
        "nhl_api_id": 20,
        "division": "Pacific",
    },
    {
        "city": "Colorado",
        "team_name": "Avalanche",
        "nhl_api_id": 21,
        "division": "Central",
    },
    {
        "city": "Edmonton",
        "team_name": "Oilers",
        "nhl_api_id": 22,
        "division": "Pacific",
    },
    {
        "city": "Vancouver",
        "team_name": "Canucks",
        "nhl_api_id": 23,
        "division": "Pacific",
    },
    {
        "city": "Anaheim",
        "team_name": "Ducks",
        "nhl_api_id": 24,
        "division": "Pacific",
    },
    {
        "city": "Dallas",
        "team_name": "Stars",
        "nhl_api_id": 25,
        "division": "Central",
    },
    {
        "city": "Los Angeles",
        "team_name": "Kings",
        "nhl_api_id": 26,
        "division": "Pacific",
    },
    {
        "city": "Arizona",
        "team_name": "Coyotes",
        "nhl_api_id": 53,
        "division": "Pacific",
    },
    {
        "city": "San Jose",
        "team_name": "Sharks",
        "nhl_api_id": 28,
        "division": "Pacific",
    },
    {
        "city": "Columbus",
        "team_name": "Blue Jackets",
        "nhl_api_id": 29,
        "division": "Metropolitan",
    },
    {
        "city": "Minnesota",
        "team_name": "Wild",
        "nhl_api_id": 30,
        "division": "Central",
    },
    {
        "city": "Winnipeg",
        "team_name": "Jets",
        "nhl_api_id": 52,
        "division": "Central",
    },
    {
        "city": "Vegas",
        "team_name": "Golden Knights",
        "nhl_api_id": 54,
        "division": "Pacific",
    },
    {
        "city": "Seattle",
        "team_name": "Kraken",
        "nhl_api_id": 55,
        "division": "Pacific",
    },
]


def populate_teams(apps, schema_editor):
    from apps.team.models import team_codes

    Team = apps.get_model("team", "Team")
    for team in default_teams:
        team["code"] = team_codes[team["city"]]
        if team["city"] == "New YorkI" or team["city"] == "New YorkR":
            team["city_name"] = "New York"
        else:
            team["city_name"] = team["city"]
        Team.objects.create(**team)


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_teams, migrations.RunPython.noop),
    ]
